image: alpine:edge

stages:
  - build

variables:
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
  - apk update
  - apk add musl-dev linux-headers meson ninja gcc scdoc ncurses
  - apk add libxkbcommon-dev pixman-dev freetype-dev fontconfig-dev
  - apk add wayland-dev wayland-protocols
  - mkdir -p subprojects && cd subprojects
  - git checkout https://codeberg.org/dnkl/tllist.git
  - git checkout https://codeberg.org/dnkl/fcft.git
  - cd ..

debug:
  stage: build
  script:
    - mkdir -p bld/debug
    - cd bld/debug
    - meson --buildtype=debug ../../
    - ninja -v -k0
    - ninja -v test

release:
  stage: build
  script:
    - mkdir -p bld/release
    - cd bld/release
    - meson --buildtype=release ../../
    - ninja -v -k0
    - ninja -v test
